buzzwords_list = [
  "django",
  "python",
  "flask", 
  "mysql", 
  "postgressql", 
  "css", 
  "javascript", 
  "git", 
  "html5",
  "machine learning",
  "mongodb",
  "pandas", 
  "sql",
  "linux",
  "numpy",
  "web scraping",
  "jquery",
  "rest apis",
  "data science",
  "docker products",
  "amazon web services",
  "software development",
  "github",
  "back-end web development",
  "java"
]
